FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY ./script /home/myapp/script/
COPY app.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/app.py
